# Generated by Django 2.2.2 on 2019-06-30 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("people", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="approved",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="approved_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="Approved by user",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="data_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("IF", "Initiation form"),
                    ("SF", "Shelter form"),
                    ("AF", "Aspiring form"),
                    ("INB", "INB"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="intensive_care",
            field=models.BooleanField(
                blank=True, help_text="Is intensive care needed?", null=True
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="life_history",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Life history of the person",
                max_length=2048,
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="Updated by user",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="is_gm_siksha_guru",
            field=models.BooleanField(verbose_name="Is Guru Maharaj Siksha Guru"),
        ),
    ]
