# Generated by Django 2.2.2 on 2019-06-30 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("regions", "0001_initial"), ("people", "0003_auto_20190630_1320")]

    operations = [
        migrations.RemoveField(model_name="person", name="permanent_address"),
        migrations.RemoveField(model_name="person", name="present_address"),
        migrations.AddField(
            model_name="person",
            name="addess_line_1",
            field=models.CharField(
                help_text="Address line 1", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="address_line_2",
            field=models.CharField(
                blank=True, help_text="Address line 2", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="locality",
            field=models.CharField(
                help_text="Locality (City, town or village)", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="permanent_addess_line_1",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Permanent address line 1"
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="permanent_address_line_2",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                null=True,
                verbose_name="Permanent address line 2",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="permanent_country",
            field=models.ForeignKey(
                help_text="Permanent country",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="permanent_persons",
                to="regions.Country",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="permanent_locality",
            field=models.CharField(
                help_text="Permanent Locality (City, town or village)",
                max_length=100,
                null=True,
                verbose_name="Permanent locality",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="permanent_state",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Permanent state"
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="permanent_zipcode",
            field=models.CharField(
                max_length=10, null=True, verbose_name="Permanent zipcode"
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="state",
            field=models.CharField(help_text="State", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="zipcode",
            field=models.CharField(help_text="Zipcode", max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="country",
            field=models.ForeignKey(
                help_text="Country",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="present_persons",
                to="regions.Country",
            ),
        ),
    ]
