# Generated by Django 2.2.2 on 2019-06-30 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("people", "0005_auto_20190630_1349")]

    operations = [
        migrations.RenameField(
            model_name="person",
            old_name="permanent_addess_line_1",
            new_name="permanent_address_line_1",
        )
    ]
