# Generated by Django 2.2.2 on 2019-07-04 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("people", "0006_auto_20190630_1355")]

    operations = [
        migrations.RemoveField(model_name="person", name="is_dob_ambiguous"),
        migrations.AddField(
            model_name="person",
            name="dob_type",
            field=models.CharField(
                choices=[("A", "Actual"), ("C", "Calculated")],
                default="A",
                max_length=1,
                verbose_name="Date of birth type",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="permanent_address_same_as_current",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="address_line_1",
            field=models.CharField(
                blank=True, help_text="Address line 1", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="locality",
            field=models.CharField(
                blank=True,
                help_text="Locality (City, town or village)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="permanent_address_line_1",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Permanent address line 1",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="permanent_country",
            field=models.ForeignKey(
                blank=True,
                help_text="Permanent country",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="permanent_persons",
                to="regions.Country",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="permanent_locality",
            field=models.CharField(
                blank=True,
                help_text="Permanent Locality (City, town or village)",
                max_length=100,
                null=True,
                verbose_name="Permanent locality",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="permanent_state",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Permanent state"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="permanent_zipcode",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Permanent zipcode"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="reference_number",
            field=models.CharField(
                editable=False,
                help_text="Unique reference number for the devotee",
                max_length=10,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="state",
            field=models.CharField(
                blank=True, help_text="State", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="zipcode",
            field=models.CharField(
                blank=True, help_text="Zipcode", max_length=10, null=True
            ),
        ),
    ]
