# Generated by Django 2.2.2 on 2019-07-04 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("people", "0008_auto_20190704_0531")]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="care_level",
            field=models.CharField(
                choices=[
                    ("A", "Aspiring"),
                    ("Z", "Shelter"),
                    ("D1", "Harinam"),
                    ("D2", "Brahmin"),
                    ("S", "Siksha"),
                    ("BTG", "Back to Godhead"),
                    ("RTK", "Ritvik"),
                    ("GB/S", "God brother or sister"),
                    ("Ex-D", "Ex Disciple"),
                    ("G", "Guidance"),
                    ("H", "Help"),
                    ("I", "Interest"),
                    ("PB", "Prayers and blessings"),
                    ("M", "Mission"),
                    ("U", "Unofficial siksha"),
                    ("C", "Special care"),
                    ("W", "Write questions"),
                    ("P", "Prayers"),
                    ("SN", "Spiritual nephew/niece"),
                ],
                help_text="Care level",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="relation_with_gm",
            field=models.CharField(
                choices=[
                    ("SS", "Spiritual son"),
                    ("SD", "Spiritual daughter"),
                    ("SSB", "Spiritual son bhakta"),
                    ("SDB", "Spiritual Daughter Bhaktin"),
                    ("SKD", "Siksha disciple"),
                    ("BTA", "Bhakta"),
                    ("BTI", "Bhaktin"),
                    ("WW", "Well wisher"),
                ],
                help_text="Relation with Guru Maharaj",
                max_length=3,
                verbose_name="Relation with Guru Maharaj",
            ),
        ),
    ]
