# Generated by Django 2.2.2 on 2019-07-04 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("people", "0012_auto_20190704_1848")]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="reference_number",
            field=models.CharField(
                editable=False,
                help_text="Unique reference number for the devotee",
                max_length=15,
                unique=True,
            ),
        )
    ]
