# Generated by Django 2.2.2 on 2019-07-04 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("people", "0013_auto_20190704_2022")]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="is_gm_siksha_guru",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Is Guru Maharaj Siksha Guru"
            ),
        )
    ]
