# Generated by Django 2.2.2 on 2019-07-05 14:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import places.fields


class Migration(migrations.Migration):

    dependencies = [("people", "0018_auto_20190705_1224")]

    operations = [
        migrations.AlterField(
            model_name="guru",
            name="code",
            field=models.CharField(db_index=True, max_length=5, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="guru",
            name="name",
            field=models.CharField(
                db_index=True, help_text="Name", max_length=255, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="gururole",
            name="name",
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="guru",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="people_meetings",
                to="people.Guru",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="aspiring_date",
            field=models.DateField(
                blank=True, db_index=True, help_text="Aspiring date", null=True
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="aspiring_place",
            field=places.fields.PlacesField(
                blank=True,
                db_index=True,
                help_text="Aspiring place",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="care_level",
            field=models.CharField(
                choices=[
                    ("A", "Aspiring"),
                    ("Z", "Shelter"),
                    ("D1", "Harinam"),
                    ("D2", "Brahmin"),
                    ("S", "Siksha"),
                    ("BTG", "Back to Godhead"),
                    ("RTK", "Ritvik"),
                    ("GB/S", "God brother or sister"),
                    ("Ex-D", "Ex Disciple"),
                    ("G", "Guidance"),
                    ("H", "Help"),
                    ("I", "Interest"),
                    ("PB", "Prayers and blessings"),
                    ("M", "Mission"),
                    ("U", "Unofficial siksha"),
                    ("C", "Special care"),
                    ("W", "Write questions"),
                    ("P", "Prayers"),
                    ("SN", "Spiritual nephew/niece"),
                ],
                db_index=True,
                help_text="Care level",
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="district",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="dob_type",
            field=models.CharField(
                choices=[("A", "Actual"), ("C", "Calculated")],
                db_index=True,
                default="A",
                max_length=1,
                null=True,
                verbose_name="Date of birth type",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="email",
            field=models.EmailField(
                blank=True, db_index=True, help_text="Email ", max_length=254, null=True
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="first_initiation_date",
            field=models.DateField(
                blank=True, db_index=True, help_text="First initiation date", null=True
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="first_initiation_place",
            field=places.fields.PlacesField(
                blank=True,
                db_index=True,
                help_text="First initiation place",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female"), ("O", "Others")],
                db_index=True,
                help_text="Gender",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="initiated_name",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Initiated name",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="is_gm_siksha_guru",
            field=models.BooleanField(
                blank=True,
                db_index=True,
                null=True,
                verbose_name="Is Guru Maharaj Siksha Guru",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="life_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AC", "Active"),
                    ("IN", "Inactive"),
                    ("LO", "Lost"),
                    ("PA", "Passed away"),
                ],
                db_index=True,
                help_text="Life status",
                max_length=2,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="locality",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Locality (City, town or village)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="marital_status",
            field=models.CharField(
                choices=[
                    ("SGL", "Single"),
                    ("ENG", "Engaged"),
                    ("SKG", "Seeking"),
                    ("MRD", "Married"),
                    ("SEP", "Separated"),
                    ("DIV", "Divorced"),
                    ("WID", "Widow"),
                ],
                db_index=True,
                help_text="Marital status",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="mobile",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Mobile number",
                max_length=17,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="name",
            field=models.CharField(db_index=True, help_text="Name", max_length=100),
        ),
        migrations.AlterField(
            model_name="person",
            name="phone",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Phone number",
                max_length=17,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="reference_number",
            field=models.CharField(
                db_index=True,
                editable=False,
                help_text="Unique reference number for the devotee",
                max_length=15,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="relation_with_gm",
            field=models.CharField(
                choices=[
                    ("SS", "Spiritual son"),
                    ("SD", "Spiritual daughter"),
                    ("SNE", "Spiritual nephew"),
                    ("SNI", "Spiritual niece"),
                    ("SSB", "Spiritual son bhakta"),
                    ("SDB", "Spiritual daughter bhaktin"),
                    ("SKD", "Siksha disciple"),
                    ("BTA", "Bhakta"),
                    ("BTI", "Bhaktin"),
                    ("WW", "Well wisher"),
                ],
                db_index=True,
                help_text="Relation with Guru Maharaj",
                max_length=3,
                verbose_name="Relation with Guru Maharaj",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="second_initiation_date",
            field=models.DateField(
                blank=True, db_index=True, help_text="Second initiation date", null=True
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="second_initiation_place",
            field=places.fields.PlacesField(
                blank=True,
                db_index=True,
                help_text="Second initiation place",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="shelter_date",
            field=models.DateField(
                blank=True, db_index=True, help_text="Shelter date", null=True
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="shelter_place",
            field=places.fields.PlacesField(
                blank=True,
                db_index=True,
                help_text="Shelter place",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="state",
            field=models.CharField(
                blank=True, db_index=True, help_text="State", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="zipcode",
            field=models.CharField(
                blank=True, db_index=True, help_text="Zipcode", max_length=10, null=True
            ),
        ),
    ]
