# Generated by Django 2.2.2 on 2019-07-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("organizations", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="temple",
            name="name",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="zone",
            name="name",
            field=models.CharField(
                db_index=True, help_text="Name", max_length=100, unique=True
            ),
        ),
    ]
