# Generated by Django 2.2.2 on 2019-07-10 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Name', max_length=255, unique=True)),
                ('code', models.CharField(db_index=True, help_text='Code', max_length=3, unique=True)),
                ('nationality', models.CharField(db_index=True, help_text='Nationality', max_length=255, unique=True)),
            ],
            options={
                'db_table': 'country',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Name', max_length=255, unique=True)),
                ('code', models.CharField(db_index=True, help_text='Code', max_length=3, unique=True)),
            ],
            options={
                'db_table': 'language',
            },
        ),
        migrations.CreateModel(
            name='Nationality',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('regions.country',),
        ),
    ]
