# Generated by Django 2.2.2 on 2019-07-04 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("regions", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="iso_code",
            field=models.PositiveIntegerField(help_text="ISO code"),
        )
    ]
