# Generated by Django 2.2.2 on 2019-07-04 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("people", "0011_auto_20190704_1847")]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="nationality",
            field=models.ForeignKey(
                blank=True,
                help_text="Nationality",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="nationals",
                to="regions.Nationality",
                to_field="nationality",
            ),
        )
    ]
