# Generated by Django 2.2.2 on 2019-07-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("people", "0015_auto_20190704_2026")]

    operations = [
        migrations.AddField(
            model_name="person",
            name="district",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="permanent_district",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
