# Generated by Django 2.2.2 on 2019-07-05 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("people", "0016_auto_20190705_1131")]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="care_level",
            field=models.CharField(
                choices=[
                    ("A", "Aspiring"),
                    ("Z", "Shelter"),
                    ("D1", "Harinam"),
                    ("D2", "Brahmin"),
                    ("S", "Siksha"),
                    ("BTG", "Back to Godhead"),
                    ("RTK", "Ritvik"),
                    ("GB/S", "God brother or sister"),
                    ("Ex-D", "Ex Disciple"),
                    ("G", "Guidance"),
                    ("H", "Help"),
                    ("I", "Interest"),
                    ("PB", "Prayers and blessings"),
                    ("M", "Mission"),
                    ("U", "Unofficial siksha"),
                    ("C", "Special care"),
                    ("W", "Write questions"),
                    ("P", "Prayers"),
                    ("SN", "Spiritual nephew/niece"),
                ],
                help_text="Care level",
                max_length=5,
            ),
        )
    ]
