# Generated by Django 2.2.2 on 2019-07-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("people", "0017_auto_20190705_1208")]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="relation_with_gm",
            field=models.CharField(
                choices=[
                    ("SS", "Spiritual son"),
                    ("SD", "Spiritual daughter"),
                    ("SNE", "Spiritual nephew"),
                    ("SNI", "Spiritual niece"),
                    ("SSB", "Spiritual son bhakta"),
                    ("SDB", "Spiritual daughter bhaktin"),
                    ("SKD", "Siksha disciple"),
                    ("BTA", "Bhakta"),
                    ("BTI", "Bhaktin"),
                    ("WW", "Well wisher"),
                ],
                help_text="Relation with Guru Maharaj",
                max_length=3,
                verbose_name="Relation with Guru Maharaj",
            ),
        )
    ]
